### ISSUE TITLE
Proprietary software licenses

### ISSUE THREAD

**Issue by Julio-Guerra** [google/licensecheck#32]
Hello,

I would like to know what's the current status regarding proprietary licenses. Are you considering to detect them (random example: by detecting some specific headers in the license file)?

I am trying to understand how can I get [my proprietary library](https://pkg.go.dev/github.com/sqreen/go-agent) to be properly handled by pkg.dev.go. The fallback to godoc.org seems no longer possible.

**Comment by jba** [comment]
The status hasn't changed. Our [license policy page](https://pkg.go.dev/license-policy) is up to date.

I suggest you pick a license from that list that expresses your intent.

**Comment by jba** [comment]
I should have mentioned that this repo holds the package that identifies licenses, which is distinct from the question whether pkg.go.dev treats them as permitting the display of docs. However, it is true that if licensecheck doesn't recognize a license, then pkg.go.dev can't recognize it either.

In any case, my advice still stands.

**Comment by rsc** [comment]
Licensecheck does now recognize a few commonly-used proprietary licenses, to give better results for people trying to understand potential new dependencies.

The bigger problem with your package is that https://github.com/sqreen/go-agent/blob/v0.15.0/LICENSE is not a license at all. A license needs to explicitly grant permission to do the things normally barred for copyrighted work, in exchange for following certain conditions. Your LICENSE file does none of that. It's also quite confusing, since "free to use" and "proprietary" are typically opposites.

As Jonathan said, the way to make your package appear in pkg.go.dev is to adopt a license that properly captures and states the conditions under which others can use it. If those conditions permit us to show it on pkg.go.dev (right now, that means it is a license the list Jonathan linked) then we will.

**Comment by Julio-Guerra** [comment]
Thanks a lot for clarifying it.
Indeed our license is incorrect. Hence my question here to try to fix it.
I'll have a look at the list of supported proprietary licenses to see what we can do.
